travis:
  secure:
    BINSTAR_TOKEN: sAcfl880bNt6GBRQvIbhID5Sv7mFL2XQpSc2C650sXbQBoUu+r6YtVJV73/0COmMlcvHakhrlXq5uMK3FBQjpmOgERH9MiCuuQAQKRKnZlinqhzh/QYQAGMwXqJ6BSnAZ45+7SwnM34X1HZ5NqJVB+Huj47tfdOgkiPhZCHoe0x/Xb9L288HhtmzN/RAG6vWd5MCACT1WdVCpaxGxgmNNKoa/1/EOLNYb4ZiXzuVMfWd91lJmnr1ReLd1cEPTfMmtQ9JM0RXrliwZNukpTsiG/E3X5v+5RTAs5aI0O9QLHCX1W1lIXAC05M3dIwZL44mXCbDExV+kxqbReMUoGIwtWnGBCBgRmd1fXjb3WW6T9SZMRIh6uoXimvh7vDRzbGBiVxkNr1MwCijkLPuQJd5AAmb8tG8PLkGaGPHtV4c8cS/K0J3w5xI5HBcwTXNpnVhkVJQYvaB8B+XTwbq77Wf3RllVnyeebehdkmM3A3KxyL+foR+mdQ4T2JyGPymDCuie3fDywGH/ks5nFHJkD4IkrZpHfDcfJfS9ujzC/m6A/YbwsvkW6HCR2G/1KLH9PH1ffTJ+KqbnLDnR2rTWmKqQ/lCdc6XYecXyoyZcfSMAuvVrZYpMDcut3LMwzosMs+T45L2I4QewvK316G/YDedpqi9cAjJGSt6MPrGnJ8O2II=
min_py_ver: '36'
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
